services:
  - type: web
    name: form-automation-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: API_KEY
        generateValue: true
      - key: CREFAZON_LOGIN
        sync: false
      - key: CREFAZON_SENHA
        sync: false
